# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f386aaa18f5e2d1544ea3da07191b191fb12927be652acd5fd53ba2461f4c76b4302068020f4e0394c2438ae1a845be802f2cea1cb614b5c7b68a676439a20d8

test:
  secret_key_base: 3e11345e00f743f6238ae147f2ff300f04de90143d3e5a8bdc123153e84430b55e6987fa3501d8909fbbc9f7d06c2c62c2ac416244e36d830e6489678728c6f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
